server:
  port: 8761   #默认端口号
eureka:
  client:
    register-with-eureka: false   #是否将当前eureka Server作为客户端进行注册。
    fetch-registry: false         #是否获取其它Eureak Server 服务的数据（同步）
    service-url:
      defaultZone: http://localhost:8761/eureak/     #注册中心的访问地址
