server:
  port: 8020   #默认端口号
spring:
  application:
    name: consumer  #当前服务在注册中心的（Eureak Server）名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   #注册中心的访问地址
  instance:
    prefer-ip-address: true  #是否将当前服务的IP注册到 Eureka Server

